### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by DemiMarie**
See individual commit messages for details.

### CODE REVIEW

**Review by marmarek — CHANGES_REQUESTED** [review]
[Use memcpy() instead of snprintf()](https://github.com/QubesOS/qubes-core-vchan-xen/pull/24/commits/fecaff9b5d2866793d9066b28df3eda2868e84e1) seems like a step backward - besides the usual "use string functions for strings", the new approach moves overflow safety from the code to the commit message (making it more risky).

The other commit is fine.

**Comment by DemiMarie** [comment]
> [Use memcpy() instead of snprintf()](https://github.com/QubesOS/qubes-core-vchan-xen/pull/24/commits/fecaff9b5d2866793d9066b28df3eda2868e84e1) seems like a step backward - besides the usual "use string functions for strings"

I am not sure what the appropriate string function would be here (unless you meant `strcat` :confused:).  `snprintf()` (which can fail in at least some implementations, though it really should not) seems wrong.

> the new approach moves overflow safety from the code to the commit message (making it more risky).

This should be caught by `-D_FORTIFY_SOURCE=2` since these are statically-sized, stack-based buffers.  Am I missing something?

> The other commit is fine.

Thanks.

**Comment by marmarek** [comment]
> `snprintf()` (which can fail in at least some implementations, though it really should not) seems wrong.

No, it does not, it is the proper function to build a string from few building parts and a format how to connect them. Return value checking was missing, but you added it in the first patch already (although the buffer size was large enough for all possible cases anyway).

**Comment by DemiMarie** [comment]
> > `snprintf()` (which can fail in at least some implementations, though it really should not) seems wrong.
> 
> No, it does not, it is the proper function to build a string from few building parts and a format how to connect them. Return value checking was missing, but you added it in the first patch already (although the buffer size was large enough for all possible cases anyway).

Apparently in some C libraries `snprintf()` allocates memory, which can fail (at least in theory).  I should file a RFE to get a guarantee that this cannot happen.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
