### PR TITLE
Add missing <stdbool.h> include

### PR DESCRIPTION
**Pull request by DemiMarie**
This caused failures in CI.

### CODE REVIEW

**Comment by tezeb** [comment]
I've made an issue for this, because I didn't think about checking for awaiting pull requests.
https://github.com/QubesOS/qubes-issues/issues/7878

**Review by marmarek — APPROVED** [review]
Approved as of ef43907f12c98621395d5feca5b5634526c6c404

**Comment by andrewdavidwong** [comment]
Please add:

Fixes https://github.com/QubesOS/qubes-issues/issues/7878

(I don't have permissions in this repo.)

**Comment by andrewdavidwong** [comment]
Never mind. @marmarek merged 1 minute before my comment. :)

**Pull request merged**
